# Site-wide markdown settings.
markdown.settings:
  type: config_object
  label: 'Markdown Settings'
  mapping:
    dependencies:
      type: config_dependencies
    parser:
      type: markdown_parser

# Markdown Parser type.
markdown_parser:
  type: mapping
  label: 'Markdown Parser'
  mapping:
    id:
      type: string
      label: 'Markdown Parser ID'
    settings:
      type: markdown_parser_settings.[%parent.id]
    extensions:
      type: sequence
      label: 'Markdown Extensions'
      sequence:
        type: mapping
        label: 'Markdown Extension'
        mapping:
          id:
            type: string
            label: 'Markdown Extension ID'
          enabled:
            type: boolean
            label: 'Markdown Extension Enabled'
          settings:
            type: markdown_extension_settings.[%parent.id]

# Parser settings.
markdown_parser_settings.*:
  type: mapping
  label: 'Markdown Parser Settings'
  mapping:
    drupal_allowed_html:
      type: string

markdown_parser_settings.league/commonmark:
  type: mapping
  label: 'CommonMark Parser Settings'
  mapping:
    allow_unsafe_links:
      type: boolean
    enable_em:
      type: boolean
    enable_strong:
      type: boolean
    html_input:
      type: string
    max_nesting_level:
      type: integer
    renderer:
      type: mapping
      mapping:
        block_separator:
          type: string
        inner_separator:
          type: string
        soft_break:
          type: string
    unordered_list_markers:
      type: string
    use_asterisk:
      type: boolean
    use_underscore:
      type: boolean

markdown_parser_settings.league/commonmark-gfm:
  type: markdown_parser_settings.league/commonmark
  label: 'CommonMark GFM Parser Settings'

# Extension settings.
markdown_extension_settings.*:
  type: mapping
  label: 'Markdown Extension Settings'

markdown_extension_settings.hash_autolinker:
  type: mapping
  label: 'Hash Autolinker'
  mapping:
    type:
      type: string
    node_title:
      type: boolean
    url:
      type: string
    url_title:
      type: boolean

markdown_extension_settings.enhanced_links:
  type: mapping
  label: 'Enhanced Links'
  mapping:
    internal_host_whitelist:
      type: string
    external_new_window:
      type: boolean
    no_follow:
      type: string

markdown_extension_settings.league/commonmark-ext-heading-permalink:
  type: mapping
  label: 'Heading Permalinks'
  mapping:
    html_class:
      type: string
    id_prefix:
      type: string
    inner_contents:
      type: string
    insert:
      type: string
    title:
      type: string

markdown_extension_settings.league/commonmark-ext-toc:
  type: mapping
  label: 'Table Of Contents'
  mapping:
    html_class:
      type: string
    max_heading_level:
      type: integer
    min_heading_level:
      type: integer
    normalize:
      type: string
    position:
      type: string
    style:
      type: string

# @todo finish adding the rest of the settings for the other parsers
