# Site-wide markdown settings.
markdown.settings:
  type: config_object
  label: 'Markdown Settings'
  mapping:
    dependencies:
      type: config_dependencies
    parser:
      type: markdown_parser

# Filter settings.
filter_settings.markdown:
  type: markdown.settings

# Markdown Parser type.
markdown_parser:
  type: mapping
  label: 'Markdown Parser'
  mapping:
    id:
      type: string
      label: 'Markdown Parser ID'
    render_strategy:
      type: markdown_render_strategy.[%parent.id]
    settings:
      type: markdown_parser_settings.[%parent.id]
    extensions:
      type: sequence
      label: 'Markdown Extensions'
      sequence:
        type: markdown_extension

# Markdown Extension type.
markdown_extension:
  type: mapping
  label: 'Markdown Extension'
  mapping:
    id:
      type: string
      label: 'Markdown Extension ID'
    enabled:
      type: boolean
      label: 'Markdown Extension Enabled'
    settings:
      type: markdown_extension_settings.[%parent.id]

# Render Strategy.
markdown_render_strategy:
  type: mapping
  mapping:
    type:
      type: string
    allowed_html:
      type: string
    plugins:
      type: sequence
      sequence:
        type: string

markdown_render_strategy.*:
  type: markdown_render_strategy

# Parser settings.
markdown_parser_settings:
  type: mapping
  label: 'Markdown Parser Settings'
  mapping:

markdown_parser_settings.*:
  type: markdown_parser_settings

# CommonMark.
markdown_parser_settings.league/commonmark:
  type: markdown_parser_settings
  label: 'CommonMark Settings'
  mapping:
    allow_unsafe_links:
      type: boolean
    enable_em:
      type: boolean
    enable_strong:
      type: boolean
    html_input:
      type: string
    max_nesting_level:
      type: integer
    renderer:
      type: mapping
      mapping:
        block_separator:
          type: string
        inner_separator:
          type: string
        soft_break:
          type: string
    unordered_list_markers:
      type: sequence
      sequence:
        type: string
    use_asterisk:
      type: boolean
    use_underscore:
      type: boolean

# CommonMark GFM.
markdown_parser_settings.league/commonmark-gfm:
  type: markdown_parser_settings.league/commonmark
  label: 'CommonMark GFM Settings'

# Parsedown.
markdown_parser_settings.erusev/parsedown:
  type: markdown_parser_settings
  label: 'Parsedown Settings'
  mapping:
    breaks_enabled:
      type: boolean
    markup_escaped:
      type: boolean
    safe_mode:
      type: boolean
    strict_mode:
      type: boolean
    urls_linked:
      type: boolean

# Parsedown Extra.
markdown_parser_settings.erusev/parsedown-extra:
  type: markdown_parser_settings.erusev/parsedown
  label: 'Parsedown Extra Settings'

# PHP Markdown.
markdown_parser_settings.michelf/php-markdown:
  type: markdown_parser_settings
  label: 'PHP Markdown Settings'
  mapping:
    empty_element_suffix:
      type: string
    enhanced_ordered_list:
      type: boolean
    hard_wrap:
      type: boolean
    no_entities:
      type: boolean
    no_markup:
      type: boolean
    predef_titles:
      type: sequence
      sequence:
        type: string
    predef_urls:
      type: sequence
      sequence:
        type: string
    tab_width:
      type: integer

# PHP Markdown Extra.
markdown_parser_settings.michelf/php-markdown-extra:
  type: markdown_parser_settings.erusev/parsedown
  label: 'PHP Markdown Extra Settings'
  mapping:
    code_attr_on_pre:
      type: boolean
    code_class_prefix:
      type: string
    fn_backlink_class:
      type: string
    fn_backlink_html:
      type: string
    fn_backlink_label:
      type: string
    fn_backlink_title:
      type: string
    fn_id_prefix:
      type: string
    fn_link_class:
      type: string
    fn_link_title:
      type: string
    hashtag_protection:
      type: boolean
    omit_footnotes:
      type: boolean
    predef_abbr:
      type: sequence
      sequence:
        type: string
    table_align_class_tmpl:
      type: string

# Extension settings.
markdown_extension_settings:
  type: mapping
  label: 'Markdown Extension Settings'

markdown_extension_settings.*:
  type: markdown_extension_settings

markdown_extension_settings.hash_autolinker:
  type: markdown_extension_settings
  label: 'Hash Autolinker'
  mapping:
    type:
      type: string
    node_title:
      type: boolean
    url:
      type: string
    url_title:
      type: boolean

markdown_extension_settings.league/commonmark-ext-external-links:
  type: markdown_extension_settings
  label: 'Enhanced Links'
  mapping:
    html_class:
      type: string
    internal_hosts:
      type: sequence
      sequence:
        type: string
    nofollow:
      type: string
    noopener:
      type: string
    noreferrer:
      type: string
    open_in_new_window:
      type: boolean

markdown_extension_settings.league/commonmark-ext-heading-permalink:
  type: markdown_extension_settings
  label: 'Heading Permalinks'
  mapping:
    html_class:
      type: string
    id_prefix:
      type: string
    inner_contents:
      type: string
    insert:
      type: string
    title:
      type: string

markdown_extension_settings.league/commonmark-ext-smart-punctuation:
  type: markdown_extension_settings
  label: 'Smart Punctuation'
  mapping:
    double_quote_opener:
      type: string
    double_quote_closer:
      type: string
    single_quote_opener:
      type: string
    single_quote_closer:
      type: string

markdown_extension_settings.league/commonmark-ext-toc:
  type: markdown_extension_settings
  label: 'Table Of Contents'
  mapping:
    html_class:
      type: string
    max_heading_level:
      type: integer
    min_heading_level:
      type: integer
    normalize:
      type: string
    placeholder:
      type: string
    position:
      type: string
    style:
      type: string
