# Site-wide markdown settings.
markdown.settings:
  type: config_object
  label: 'Markdown Settings'
  mapping:
    parser:
      type: markdown_parser

# Markdown Parser type.
markdown_parser:
  type: mapping
  label: 'Markdown Parser'
  mapping:
    id:
      type: string
      label: 'Markdown Parser ID'
    settings:
      type: markdown_parser_settings.[%parent.id]
    extensions:
      type: sequence
      label: 'Markdown Extensions'
      sequence:
        type: mapping
        label: 'Markdown Extension'
        mapping:
          id:
            type: string
            label: 'Markdown Extension ID'
          enabled:
            type: boolean
            label: 'Markdown Extension Enabled'
          settings:
            type: markdown_extension_settings.[%parent.id]

# Parser settings.
markdown_parser_settings.*:
  type: mapping
  label: 'Markdown Parser Settings'
markdown_parser_settings.league/commonmark:
  type: mapping
  label: 'CommonMark Parser Settings'
  mapping:
    # @todo finish adding the rest of the config settings
    # @see https://commonmark.thephpleague.com/1.4/configuration/
    html_input:
      type: string
    allow_unsafe_links:
      type: boolean
    max_nesting_level:
      type: integer
    renderer:
      type: mapping
      mapping:
        block_separator:
          type: string
        inner_separator:
          type: string
        soft_break:
          type: string

markdown_parser_settings.league/commonmark-gfm:
  type: markdown_parser_settings.league/commonmark
  label: 'CommonMark GFM Parser Settings'

# Extension settings.
markdown_extension_settings.*:
  type: mapping
  label: 'Markdown Extension Settings'
markdown_extension_settings.hash_autolinker:
  type: mapping
  label: 'Hash Autolinker'
  mapping:
    type:
      type: string
    node_title:
      type: boolean
    url:
      type: string
    url_title:
      type: boolean

markdown_extension_settings.enhanced_links:
  type: mapping
  label: 'Enhanced Links'
  mapping:
    internal_host_whitelist:
      type: string
    external_new_window:
      type: boolean
    no_follow:
      type: string

# @todo finish adding the rest of the settings for the other parsers
