markdown.settings:
  type: config_object
  label: 'Markdown Settings'
  mapping:
    parser:
      type: string
      label: 'Default markdown parser'

    parsers:
      type: mapping
      label: 'Default markdown parser settings'
